### PR TITLE
Add a link to the `Destination` object interface in the documentation

### PR DESCRIPTION
**Pull request by PierreFritsch**
by reusing the existing link to the `Destination` object above

so that developers trying to mock destinations can find out what parameters are supported and how they are capitalized.

This is useful because the destinations can't be taken over directly from the destination service, which returns them in the format: 

```
    "destinationConfiguration": {
        "Name": "...",
        "Type": "HTTP",
        "URL": "https://.../",
        "Authentication": "OAuth2ClientCredentials",
        "ProxyType": "Internet",
        "Description": "...",
        "clientId": "...",
        "tokenServiceURL": "https://...authentication.sap...ondemand.com/oauth/token",
        "clientSecret": "..."
    },
    "authTokens": [
        {
            "type": "bearer",
            "value": "...",
            "http_header": {
                "key": "Authorization",
                "value": "Bearer ..."
            },
            "expires_in": "43199",
            "scope": "..."
        }

```

while the [`Destination` object](https://sap.github.io/cloud-sdk/api/1.32.0/interfaces/sap_cloud_sdk_core.destination) in SAP Cloud SDK doesn't understand uppercase `Name`, `Type`, `URL`, but expects lowercase `name`, `type`, and `url`. 
Based on these differences in capitalization, manual "mapping" work has to be performed to map the attributes e.g. `tokenServiceURL` (from the destination service) to `tokenServiceUrl` (in the destination object from SAP Cloud SDK).

### CODE REVIEW

**Comment by artemkovalyov** [comment]
Thanks for the PR, @PierreFritsch . We'll review it shortly and get back to you.

**Comment by FrankEssenberger** [comment]
Ups, I already had a look and forgot to write a comment. I think an issue is the hard coded version (1.32.0):
```
<pathname:///api/1.32.0/interfaces/sap_cloud_sdk_core.destination>
```

We should have a link using some `latest` in the path pointing always to the latest documentation. I asked @marikaner about that but she had problems doing this in the past due to some docasaurous issue.

But this is not part of this PR but a general issue. Regarding the content it worked locally (to the usual extend) so this would be fine for me. The quotes in the link looked a bit strange to me:

image

but I have no strong opnion there.

**Review by FrankEssenberger — APPROVED** [review]
LGTM - please resolve the conflict i.e. adding the new auth method which was added to the list.

**Comment by PierreFritsch** [comment]
Merge conflict resolved

**Comment by artemkovalyov** [comment]
@PierreFritsch, thanks for taking care. I updated our docs a tiny bit to always refer to the latest API docs #375. I also added there what you proposed in your PR. I'll keep this one open for reference. I'll keep you posted when changes are factored in.

**Comment by artemkovalyov** [comment]
@PierreFritsch, I've incorporated these changes into a bigger PR and will be closing this now. Thanks a lot for contributing and sorry it took a bit longer to process this.

**Pull request closed without merging**
