### PR TITLE
docs: Align redirection

### PR DESCRIPTION
**Pull request by marikaner**
## Context

The existing generator redirect was broken. All of the redirect pages displayed a debug message saying "Feature Title". I think telling the user that this is about "Redirecting" is more straight forward. Also, because we had some very complicated links, I aligned links with file names.
I tested this locally and all links still work.

## Definition of Done

Please consider all items and remove only if not applicable.

- [ ] Tests created/adjusted for your changes.
- [ ] Release notes updated.
  * Provide sufficient context so that each entry can be understood on its own.
  * Be specific about names of functions, classes, modules, etc.
  * Describe when or where this is relevant
  * Use indicative and present tense. For example, write "Provide function `name` that does X in order to Y" over "Now X can be done by calling a new function".
- [ ] PR title adheres to [conventional commit guidelines](https://www.conventionalcommits.org) (please note that only `fix:` and `feat:` will end up in the release notes)
- [ ] If applicable: Properly documented (JSDoc of public API)
- [ ] If applicable: Check if `node run doc` still works.

### CODE REVIEW

**Comment by jjtang1985** [comment]
I have some stupid questions. 
- How could you reproduce to see the "Feature Title"?
- Why do we have to use the redirect md files?
For example, `use-typed-odata-v4-client-for-javascript-and-typescript` will redirect to `odata-v4-client`. Couldn't we just link to `odata-v4-client` instead of `use-typed-odata-v4-client-for-javascript-and-typescript`?

**Comment by marikaner** [comment]
> I have some stupid questions.
> 
> * How could you reproduce to see the "Feature Title"?
> * Why do we have to use the redirect md files?
>   For example, `use-typed-odata-v4-client-for-javascript-and-typescript` will redirect to `odata-v4-client`. Couldn't we just link to `odata-v4-client` instead of `use-typed-odata-v4-client-for-javascript-and-typescript`?

You can try for example: https://sap.github.io/cloud-sdk/docs/js/features/odata/use-typed-odata-client-for-js, but you have to look quickly because it jumps to the redirected page after half a second.

I think the redirects are there for historic reasons. If the links were sent to anyone before, they would be dead otherwise. I tried to find out whether there is a shorter notation for this, maybe in a central place, but I didn't find anything.

**Comment by jjtang1985** [comment]
> but you have to look quickly because it jumps to the redirected page after half a second.

Yes, it's redirected to "Page Not Found" 😞

**Review by jjtang1985 — APPROVED** [review]

**Comment by marikaner** [comment]
> > but you have to look quickly because it jumps to the redirected page after half a second.
> 
> Yes, it's redirected to "Page Not Found" 😞

Oh, I didn't even realize. I hope after my changes it works, if not, you will get another PR ;)

**Pull request merged**
