### PR TITLE
edit release notes for v1.18.0

### PR DESCRIPTION
**Pull request by jordan40**

### CODE REVIEW

**Comment by FrankEssenberger** [comment]
Is this supposed to be merged already?

**Comment by jjtang1985** [comment]
I would keep it, since the doc does not contain the open source one.
But we can also merge and update it.

**Comment by FrankEssenberger** [comment]
No it is fine to keep it open, then we should add the label.

**Comment by jordan40** [comment]
Do you want the move to open source to be part of the release notes? Feel free to edit this PR with the content.

**Comment by jordan40** [comment]
need to reopen this PR

**Pull request closed without merging**
