### PR TITLE
docs(js): add path templating doc to generate-openapi-client.mdx

### PR DESCRIPTION
**Pull request by ZhongpinWang**
## What Has Changed?

Ref: SAP/cloud-sdk-js#2358
Closes: SAP/cloud-sdk-backlog#52

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

### CODE REVIEW

**Review by marikaner — CHANGES_REQUESTED** [review]
Sorry for coming up with this so late, I am wondering whether this documentation is really necessary. It basically states, that incorrect path parameters as of the OpenAPI specification are not supported and if parameters are missing the generation will fail.

Feel free to disagree, but I think we should not add this to our documentation, because it adds too many details, that are not relevant enough. @jjtang1985, @frank-essenberger, @florian-richter, @deekshas8, @tomfrenken opinions?

**Comment by florian-richter** [comment]
Agreed, I don't think we need to inform users about this. I think this may be a case of "it just works" and you don't need to worry about it. Crazy edge cases (like `{para/m}`) can be handled in answers to support tickets.

@marikaner Good that you caught it now, even though we should have realized this before Zhongpin spent time on this...

**Comment by FrankEssenberger** [comment]
For me it would be fine to close it  since it states: For correct files it works. If we keep it we should add a bit more like `For valid spec files you should not have to do something. But if you face errors of the kind XYZ this is related to the follwing requirements`.

**Comment by marikaner** [comment]
Thank you for your feedback, I will go ahead and close this then.

**Pull request closed without merging**
