### PR TITLE
chore: Update and loosen remaining dependency versions

### PR DESCRIPTION
**Pull request by marikaner**
Almost done, I will try to do the left overs in one PR.
This update includes an update of `http-proxy-agent` and `https-proxy-agent`, for which I had to adjust types in some places. As this was a change from `https.Agent` to `http.Agent`, this is merely broadening our scope and is not a breaking change.

### CODE REVIEW

**Comment by marikaner** [comment]
> I would be 100% satisfied, if we could have a proxy test with a https destination e.g. https://example.com instead of http://example.com

I added a proxy test in general, as discussed.

**Comment by FrankEssenberger** [comment]
> > I would be 100% satisfied, if we could have a proxy test with a https destination e.g. https://example.com instead of http://example.com
> 
> @FrankEssenberger As discussed, I reenabled the proxy tests here: #70.

But this is "only" a test asking if the request is executed with certain proxy settings. Is it planed to get the test including really to servers and seeing it e2e planed to be run as an e2e test? I am not sure now.

**Comment by marikaner** [comment]
> > > I would be 100% satisfied, if we could have a proxy test with a https destination e.g. https://example.com instead of http://example.com
> > 
> > 
> > @FrankEssenberger As discussed, I reenabled the proxy tests here: #70.
> 
> But this is "only" a test asking if the request is executed with certain proxy settings. Is it planed to get the test including really to servers and seeing it e2e planed to be run as an e2e test? I am not sure now.

I now added another test, that tests explicitly that an httpsAgent is set for https requests (I did not consider that in the other PR).
On the one hand you are right, it would be great to also check the underlying behavior for https. On the other hand, it turned out to be quite difficult to set it up (but maybe this is just me). We are testing the general behavior with http and we are checking our assumptions for https as well, which was not test before. This should be enough for this PR, because no logic has changed, only types have been generalized.
Let's discuss offline whether we should follow up on an additional test. I created a ticket for that.

**Comment by FrankEssenberger** [comment]
Yes let's discuss after standup today.

**Pull request merged**
