### PR TITLE
Update Readme in core

### PR DESCRIPTION
**Pull request by artemkovalyov**
## Context

Update section on Documentation and Helpful links.

### CODE REVIEW

**Comment by marikaner** [comment]
@artem, you should probably add the same to the other packages (utli, test-util, generator, analytics).

**Comment by artemkovalyov** [comment]
Doing them 1 by 1 to make PRs small. I also wasn't sure it all uniform.

**Comment by marikaner** [comment]
> Doing them 1 by 1 to make PRs small. I also wasn't sure it all uniform.

C'mon 5 readmes with the exact same changes is still small ;)

**Comment by artemkovalyov** [comment]
After I know you're happy with the update it's easier to put bulk effort and update everything.
By the way, despite you seemingly approved this I still can't merge regardless of green tests.

**Comment by artemkovalyov** [comment]
@marikaner, I pushed updates for other modules as well.

**Pull request merged**
