### PR TITLE
[Fix] Renaming to .mdx broke the Documentation Build

### PR DESCRIPTION
**Pull request by FrankEssenberger**
## Context

I renamed the .md files consistently to .mdx but this broke the build. This PR tries to fix it.

### CODE REVIEW

**Comment by FrankEssenberger** [comment]
Checked it locally. `npm run build` worked after deleting the `docusaurus` folder. Please go ahead and merge so that others are not blocked by my mistake

**Review by artemkovalyov — APPROVED** [review]
As I know by default Docusaurus considers MD and MDX as well. At least react components work fine. That's why I was keeping it simple before we need any advanced functionality unlocked by explicit MDX resolution. I'll check the docs regarding this again.

**Comment by FrankEssenberger** [comment]
Per default they have a `.mdx` parser. At least this is how I understood it and also some of the things we use already are not plain .md.

**Comment by artemkovalyov** [comment]
@FrankEssenberger , you're right, and probably this default parsing does the tick. MDX should also work. Do you have anything not yet covered currently without having MDX resolution?

**Comment by FrankEssenberger** [comment]
I hope not. I wrote a little script moving all `.md` file in the doc folder.

**Pull request merged**
