### PR TITLE
chore: Upgrade cds

### PR DESCRIPTION
**Pull request by marikaner**
## Context

Upgrade cds to v4 for the e2e tests

## Definition of Done

Please consider all items and remove only if not applicable.

- [ ] Tests created/adjusted for your changes.
- [ ] Release notes updated.
  * Provide sufficient context so that each entry can be understood on its own.
  * Be specific about names of functions, classes, modules, etc.
  * Describe when or where this is relevant
  * Use indicative and present tense. For example, write "Provide function `name` that does X in order to Y" over "Now X can be done by calling a new function".
- [ ] PR title adheres to [conventional commit guidelines](https://www.conventionalcommits.org) (please note that only `fix:` and `feat:` will end up in the release notes)
- [ ] If applicable: Properly documented (JSDoc of public API)
- [ ] If applicable: Check if `node run doc` still works.

### CODE REVIEW

**Comment by jjtang1985** [comment]
switching to v4 cds needs additional runtime dependencies, that's why the pipeline fails.
also check the important docs here when necessary: https://cap.cloud.sap/docs/releases/july20#cds-js

**Comment by FrankEssenberger** [comment]
The colleagues were also very friendly so I guess if we ask them for a meeting or help in the migration process they will help.

**Comment by marikaner** [comment]
> switching to v4 cds needs additional runtime dependencies, that's why the pipeline fails.
> also check the important docs here when necessary: https://cap.cloud.sap/docs/releases/july20#cds-js

Locally I probably already had a db, that's why it was not complaining locally. I fixed it now. Let's see if it works.

**Comment by marikaner** [comment]
> The colleagues were also very friendly so I guess if we ask them for a meeting or help in the migration process they will help.

Not necessary, worx ;)

**Comment by marikaner** [comment]
`$batch` still does not comply with the standard in cds v4, therefore I created a ticket here: https://github.wdf.sap.corp/cap/issues/issues/6116. We should adjust the test once the ticket is done.

**Review by FrankEssenberger — APPROVED** [review]

**Pull request merged**
