### PR TITLE
Add Note About Destination Caching

### PR DESCRIPTION
**Pull request by Johannes-Schneider**
## What Has Changed?

Explain how the SDK minimizes runtime overhead of looking up destinations by using caching internally.

## Manual Checks?

- [x] Text adheres to the style guide (`vale docs/`)
  - Every sentence is on its own line
  - Headings use [title capitalization](https://capitalizemytitle.com/style/AP/#) (applies also to the sidebar and title of a document)
  - You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)
- [x] You checked your spelling and grammar (consider using Grammarly, see `CONTRIBUTING.md`)
- [x] You formatted all changed files with prettier (`npm run prettier`)
- [x] You tested if the documentation still builds (`npm run build`)
- [x] You verified all new and changed links still work (changing the `id` or name of a file can break links)
- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.

### CODE REVIEW

**Review by MatKuhr — COMMENTED** [review]
great addition, I would add exactly how long destinations are cached because this is crucial to know e.g. when updating an destination - there is a big difference between 5 minutes and 5 days ;) 

I think it's 6 minutes, but maybe check to be sure

**Review by newtork — APPROVED** [review]

**Comment by newtork** [comment]
I agree with Matthias here. I think 5min should be mentioned here.
image

**Comment by Johannes-Schneider** [comment]
> Fun fact: there seems to be no cache for Neo.

Is there a reason for that inconsistency? If so, should that also be mentioned here in the docs?

**Comment by newtork** [comment]
> Is there a reason for that inconsistency?
People only complained about slow destination service on Cloud Foundry. Seems like they never cared about Neo.

> If so, should that also be mentioned here in the docs?

I would only mention the cache duration for Cloud Foundry. The fact that it's missing for Neo, I would leave unmentioned.

**Comment by MatKuhr** [comment]
I think on NEO the platform libraries that handle the destination logic might apply a cache. But I don't know for certain.

**Pull request merged**
