### PR TITLE
fix: v2 docs links

### PR DESCRIPTION
**Pull request by deekshas8**
## What Has Changed?

Closes https://github.com/SAP/cloud-sdk-backlog/issues/1034

Many links in v2 docs point to /v3/. This PR fixes them.
Updated the Styleguide to add information on path notation

## Manual Checks?

- [ ] Check spelling and grammar, e.g., using Grammarly.
- [ ] Verify links still work, e.g., if `id` or the name of a file is changed.
- [ ] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a feature is added.

### CODE REVIEW

**Review by marikaner — CHANGES_REQUESTED** [review]
Looks good, but we should add the same changes to v3, otherwise when we start working on v4 we will have the same issue.

**Comment by deekshas8** [comment]
> but we should add the same changes to v3, otherwise when we start working on v4 we will have the same issue.

Yes, that's correct. I adjusted it for v3 as well. I also updated it to use the doc id instead of <filename>.mdx

**Review by FrankEssenberger — COMMENTED** [review]
LGTM

**Review by FrankEssenberger — APPROVED** [review]
LGTM

**Pull request merged**
