### PR TITLE
Make vale treat errors as failure

### PR DESCRIPTION
**Pull request by artemkovalyov**
## What Has Changed?

I think with action warnings would be failing the PR.

### CODE REVIEW

**Review by jjtang1985 — APPROVED** [review]

**Review by jjtang1985 — CHANGES_REQUESTED** [review]
I found [this](https://errata-ai.github.io/vale-server/docs/ini).
> CI builds will only fail on error-level alerts.
MinAlertLevel = warning

So I think the current config is fine.

**Review by florian-richter — CHANGES_REQUESTED** [review]
When I created the config file, the "MinAlertLevel" also filtered out any finding below the threshold. So no warnings would be shown at all.

In my opinion, warnings should be shown but not break the pipeline (ideally there would be a threshold like 50/100/200 warnings total).

**Comment by artemkovalyov** [comment]
@florian-richter, @jjtang1985, We had already suppressed warnings some time ago. They don't help. Our PRs will be overcroweded with suggestions. I'm suggesting that addressing warnings should be a part of local development.

**Review by jjtang1985 — APPROVED** [review]

**Comment by florian-richter** [comment]
@artemkovalyov I disagree and would mention two points:
- this config would hide warnings locally (unless people overwrite the config locally which I find unlikely)
- not even displaying warnings reduces the usefulness of vale

When creating the ruleset my rule of thumb was:
- Errors: Must fix errors
- Warnings: Rules with high impact and low false-positive rate or medium impact and no false positives
- Suggestions: Rules with medium to low impact and low to medium false positive rate

There are a number of warnings (e.g. Sentence Case Titles) that I find rather essential but they have a slight chance of false positives so I would avoid making them errors. Not showing the warnings at all would lead to a degradation of consistency in my eyes.

LIke I said, this is my opinion and I understand we may choose a different path if the majority agrees.

**Comment by artemkovalyov** [comment]
@florian-richter, are you ok with the proposal?

**Comment by florian-richter** [comment]
> @florian-richter, are you ok with the proposal?

See my [comment above](https://github.com/SAP/cloud-sdk/pull/216#issuecomment-818646859). I dissent but you may overrule if the team agrees.

**Comment by artemkovalyov** [comment]
@florian-richter, I now see your point as config wasn't changed before, and locally all the warnings would have been visible.
Hopefully, with only changed lines processed by vale there PR won't be too polluted with warning and they'll be meaningful indeed.

I'll close this PR.

@jjtang1985, FYI.

**Pull request closed without merging**
