### PR TITLE
Add feedback link

### PR DESCRIPTION
**Pull request by marikaner**
Adds a feedback link. Closes https://github.com/SAP/cloud-sdk-backlog/issues/464

### CODE REVIEW

**Comment by deekshas8** [comment]
[q] Does the banner go away once the user has done the survey?

**Review by deekshas8 — APPROVED** [review]

**Comment by FrankEssenberger** [comment]
image

**Review by jjtang1985 — APPROVED** [review]
Looks good as a short survey.
Do we have a plan to check the results?

**Comment by marikaner** [comment]
> Member

Unfortunately not.

**Pull request merged**
